# Generated by Django 3.1 on 2020-08-19 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0002_auto_20200819_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 5, 56, 292852)),
        ),
    ]
