# Generated by Django 3.1 on 2020-09-07 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0006_auto_20200907_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 47, 52, 190880)),
        ),
    ]
