# Generated by Django 3.1 on 2020-09-07 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0007_auto_20200907_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 18, 32, 44, 520613)),
        ),
    ]
