# Generated by Django 3.1 on 2020-09-08 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0009_auto_20200907_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 18, 33, 41, 156072)),
        ),
    ]
