# Generated by Django 3.1 on 2020-11-11 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0011_auto_20201111_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 13, 53, 57, 161859)),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 13, 53, 57, 163109)),
        ),
    ]
