# Generated by Django 3.1 on 2020-11-12 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0012_auto_20201111_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 11, 24, 14, 322003)),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 16, 24, 14, 322003, tzinfo=utc)),
        ),
    ]
