# Generated by Django 3.1 on 2021-03-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0014_auto_20210104_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botchkresults',
            options={'verbose_name_plural': 'BotChkResults'},
        ),
        migrations.AlterField(
            model_name='botchkresults',
            name='pass_mathtest',
            field=models.BooleanField(default=False, help_text='any order, separated by commas'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(help_text='Need http/s prefix, best to cut and paste from a website'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, help_text='Pick new picture or use default picture', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Need http/s prefix, best to cut and paste from website'),
        ),
    ]
