"""
Django settings for InteractiveMath_prj project.

Generated by 'django-admin startproject' using Django 3.1 and upgraded via Gemini 

"""

from pathlib import Path
import os
from csp.constants import SELF, NONCE


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

#Can use cloud or local server (latter for test, former for test and deployment) for static code or static binary files
USE_CLOUD_BUCKET = os.environ.get('USE_CLOUD_BUCKET','False')
#location where static code is located in cloud
CLOUD_URL_CODE = os.environ.get('CLOUD_URL_CODE','')
#location where static binaries are located in cloud
CLOUD_URL_BINARY = os.environ.get('CLOUD_URL_BINARY','')
#for dev testing, may use local static code or use cloud static code, here we choose
USE_LOCAL_CODE = os.environ.get('USE_LOCAL_CODE', 'False')

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
STATIC_DIR = os.path.join(BASE_DIR,"static")
#*****make a symbolic link to test how it works *****
# this is the actual location of desired binaries
BINARIES_LOC_str = os.environ.get('STATIC_BINARIES_DIR','')

#this is the destination location and it only happens in local debug, dont want symlink in production
SYMLINK_BINARIES_dir = os.path.join(STATIC_DIR,"static_binaries")
if DEBUG:
    #create symbolic link so everything gets served by runserver as though it was under main project 
    if (not (os.path.exists(SYMLINK_BINARIES_dir))):
        os.symlink(BINARIES_LOC_str, SYMLINK_BINARIES_dir)
    STATICFILES_DIRS = [STATIC_DIR]
else:
    #https://stackoverflow.com/questions/24022558/differences-between-staticfiles-dir-static-root-and-media-root
    #STATIC_ROOT is needed by deployment server for collectstatic, its where static files will be stored
    # this directory will already have some static files, need to put the static_binaries in their expected place
    STATIC_ROOT = os.path.join(STATIC_DIR,"static_binaries")
    # STATICFILES_DIR used by collectstatic to serve other directories under deployment
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    #Adding STATIC_DIR so that we can inline using django-inline-static and the 'python manage.py findstatic myfile' works
    STATICFILES_DIRS = [BINARIES_LOC_str, STATIC_DIR]

RECAPTCHA_SECRET_KEY = os.environ.get('G_RECAPTCHA_V3_SECRET_KEY','')
RECAP_PUBLIC_KEY = os.environ.get('G_RECAPTCHA_V3_PUBLIC_KEY','')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('INT_MATH_SECRET_KEY','')

#signed URL for static code bucket
SIGN_URL_SECRET_CODE = os.environ.get('SIGN_URL_SECRET_CODE','dev-placeholder')
#signed URl for static binaries bucket
SIGN_URL_SECRET_BIN = os.environ.get('SIGN_URL_SECRET_BIN','dev-placeholder')

#setup the SMTP server for use in sending successful messages, based on https://help.pythonanywhere.com/pages/SMTPForFreeUsers/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
#WEBSITE_EMAIL_ADDR is a gmail account and SMTP_APP_PSWD is the app password for that gmail account
EMAIL_HOST_USER = os.environ.get('WEBSITE_EMAIL_ADDR','') 
#NOTE:  app password disabled every time gmail acct changes
EMAIL_HOST_PASSWORD = os.environ.get('SMTP_APP_PSWD','') 
EMAIL_USE_TLS = True

if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
else:
    CURRENT_HOST = os.environ.get('CURRENT_URL','') # Expects 'www.mainsite.org'
    ALLOWED_HOSTS = [
        CURRENT_HOST,
        'interactablemath.org',
        'interactablemath.com',
        'interactivemath.org',
    ]
    # Clean up any None values if the env var is missing
    ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]
    # Django 5.x requires the scheme (https://)
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]
    # when using proxy, user should see domain it requests, not internal versions
    USE_X_FORWARDED_HOST = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'int_math.apps.IntMathConfig',  # Use this rather than just 'int_math'
]
if DEBUG:
    INSTALLED_APPS.insert(0, 'debug_toolbar')
#Sessionmiddleware must be before AuthenticationMiddleware    
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]
if DEBUG:
    # Safely insert after CommonMiddleware
    index = MIDDLEWARE.index('django.middleware.common.CommonMiddleware') + 1
    MIDDLEWARE.insert(index, 'debug_toolbar.middleware.DebugToolbarMiddleware')

X_FRAME_OPTIONS = 'SAMEORIGIN'  #so the legal stuff will operate with correct headers

#this won't help us since we don't allow user upload of files but will kill a owasp zap low error
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

#django 5.2
#django-csp needs the flat, not dictionary format
# settings.py
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": [SELF],
        "font-src": [
            SELF, 
            "https://cdn.jsdelivr.net/npm/mathjax@3/",  #for mathjax
        ],
        "style-src": [SELF, NONCE],
        "script-src": [SELF, NONCE],
        "style-src-elem": [
            SELF,
            "https://getbootstrap.com",
            "https://code.jquery.com",
            "https://staticcode.interactablemath.org",
            NONCE,
            "'sha256-JLEjeN9e5dGsz5475WyRaoA4eQOdNPxDIeUhclnJDCE='", # for mathjax, will change on upgrades
            "'sha256-mQyxHEuwZJqpxCw3SLmc4YOySNKXunyu2Oiz1r3/wAE='",  #for mathjax
            "'sha256-OCf+kv5Asiwp++8PIevKBYSgnNLNUZvxAp4a7wMLuKA='",   # for mathjax
            "'sha256-trR7JwveKVMgnodBl3ld+T42sD/8Nob3daQDT5n8sYw='",  # for mathjax
        ],
        "style-src-attr": [SELF, "'unsafe-inline'"],
        "worker-src": [SELF, "blob:"],
        "script-src-elem": [
            SELF,
            "https://www.googletagmanager.com",
            "https://www.google.com",
            "https://getbootstrap.com",
            "https://www.gstatic.com",
            "https://ajax.googleapis.com",
            "https://cdnjs.cloudflare.com",
            "https://cdn.jsdelivr.net",
            "https://staticcode.interactablemath.org",
            "https://www.youtube.com",
            "https://ytimg.com",
            NONCE,
        ],
        "img-src": [
            SELF,
            "https://code.jquery.com",
            "https://*.ytimg.com",
            "https://*.google.com",
            "data:",
            "https://staticbinary.interactablemath.org",
            "https://staticcode.interactablemath.org",
        ],
        "frame-src": [
            SELF,
            "data:",
            "https://www.google.com",
            "https://www.gstatic.com",
            "https://staticbinary.interactablemath.org",
            "https://www.youtube.com",
            "https://www.youtube-nocookie.com",
        ],
        "media-src": [SELF, "https://staticbinary.interactablemath.org"],
        "frame-ancestors": [SELF, "https://www.google.com"],
        "connect-src": [
            SELF,
            "https://www.google.com",
            "https://getbootstrap.com",
            "https://www.gstatic.com",
            "https://cdnjs.cloudflare.com",
            "https://staticbinary.interactablemath.org",
        ],
        "form-action": [SELF],
    }
}


# These will ONLY report to the console/logger (useful for debugging)
# CONTENT_SECURITY_POLICY_REPORT_ONLY = {
#     "DIRECTIVES": { ... new rules you are testing ... }
# }

ROOT_URLCONF = 'InteractiveMath_prj.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates', # Updated to Pathlib style for Django 5.2
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Add this line to make {{ CSP_NONCE }} available globally
                'csp.context_processors.nonce',
            ],
        },
    },
]

WSGI_APPLICATION = 'InteractiveMath_prj.wsgi.application'

# for debug only
INTERNAL_IPS = [
    '127.0.0.1',
    ]
    
if not DEBUG:
    # we are deployed, not in localserver
    # security for https deployment
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False  # now that we are using Cloudflare for reverse proxy and https, don't do it here
    #may need to increase this from 1 hour (3600) to 1 year (31536000) once all is working.  This forces https only
    SECURE_HSTS_SECONDS= 604800 # 1 week.  # 86400 is 1 day and 31536000  # Recommended: 1 year (in seconds)  -- this used to be 3600 or 1 hour
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # hstspreload.org recommends we set this to false--minimal protection gain from true but max hassle.
    SECURE_HSTS_PRELOAD = False
    
    #defaulted already to true but repeating here
    SESSION_COOKIE_HTTPONLY = True
    #more secure csrf cookie--to pass owasp test
    CSRF_COOKIE_HTTPONLY = True
    CSRF_TRUSTED_ORIGINS = [f"https://{CURRENT_HOST}"] # since we are behind a reverse proxy 
    #since on reverse proxy, avoid csrf verify fail on forms.  Essential 
    #for preventing infinite redirect loops when your proxy terminates SSL and communicates with Django over HTTP
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#required for upgrade to django3.2.25, as per gemini AI
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# upgrade to django 4.2 and py 3.10
USE_TZ = True
TIME_ZONE = 'UTC'  # Best practice: keep DB in UTC, convert in views/templates

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
